### ISSUE TITLE
"NameError: name 'Nitro_Diffusion' is not defined"

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#1]
Please, can somebody help me? I keep getting this error shortly after I run the diffusion in the collab... I have no idea what am I supposed to do, I tried updating to python 3.10 but that didn't help, I also tried running the first command paragraph that says you are supposed to run it if you get any errors, but that didn't help either... it just suddenly stopped working... if someone had an answer it would be most appreciated! Thank you very much!😖☹️

Here is a link to the Error Message that I'm getting:
![agfadgfg](https://user-images.githubusercontent.com/118744157/203072420-4a7989e6-1958-4821-b91a-127f0f336f35.png)

**Comment by misobarisic** [comment]
The error has been fixed in the latest commit

**Comment by misobarisic** [comment]
Make sure to use the latest version under "File" -> "Revision history"
