### ISSUE TITLE
Localtunnel option

### ISSUE THREAD

**Issue by reidrigo** [misobarisic/Diffusion-UI#10]
WOuld be possible to add a option to use the LocalTunnel too? Since the Gradio are having a lot of 504 problems this past days. 
Thanks so much for your work!

**Comment by misobarisic** [comment]
Added

**Comment by misobarisic** [comment]
Tried using localtunnel. It quickly times out and refuses to work. ngrok may be a viable alternative. It requires additional setup on the user's behalf though.
