### ISSUE TITLE
Error: Your local changes to the following files would be overwritten by checkout: train.py

### ISSUE THREAD

**Issue by bay900** [misobarisic/Diffusion-UI#11]
Hi, I have the following options checked, and I keep getting the error below

-run in gdrive
-xformers
-tag complete
-hypernetworks
-anything 3
-all the lora

Also, can I leave the lora unchecked on subsequent runs? New ones kept getting downloaded with a number suffix to Google Drive.

2023-02-07 08:27:35 (57.0 MB/s) - ‘/content/drive/MyDrive/AI/stable-diffusion-webui/models/Stable-diffusion/anything-v4.0.vae.pt’ saved [822802803/822802803]

/content/drive/MyDrive/AI/stable-diffusion-webui
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Commit hash: b915325c1eb5f8d8e9e22d156c9e9869e47c8ddf
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 162, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout {name}'s hash: {commithash}.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting

**Comment by bay900** [comment]
I tried using a different Google account and it ran properly this time. What could possibly be the issue?

**Comment by misobarisic** [comment]
train.py seems to have been changed somehow which prevented the startup mechanism to change branches since it wasn't stashed. Don't know what caused the change in train.py though. 🤔
