### ISSUE TITLE
Using a different VAE

### ISSUE THREAD

**Issue by bay900** [misobarisic/Diffusion-UI#12]
Hi, is it possible to use a different VAE?

I'd like to try using orangemix.vae.pt since it's in the "How to use" section of AbyssOrangeMix2 (AOM2). What do I need to edit if it's possible?

**Comment by misobarisic** [comment]
I'll add a way to use user specified vae. For the time being any4 vae works good enough with aom2 in my opinion.

**Comment by bay900** [comment]
Thanks, looking forward to it. The results were pretty good indeed.
