### ISSUE TITLE
i cant choose the model

### ISSUE THREAD

**Issue by patepix3** [misobarisic/Diffusion-UI#18]
when im in the ui and i try to change the checkpoint, it does an error, how can i solve this?
![imagem_2023-02-22_203523708](https://user-images.githubusercontent.com/126114614/220787752-9c43ab8a-e70a-4d9d-9fcb-234baf6c9f07.png)

**Comment by patepix3** [comment]
the checkpoint is the model, right?

**Comment by misobarisic** [comment]
Yes, it is. The issue might be a particular model in question. Which ones do you have selected?

**Comment by patepix3** [comment]
also, is there any video explaining the features or configs to this colab? i really wanna get into ai image gen but idk how to start because there is a lot
