### ISSUE TITLE
"No checkpoints found"

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#2]
When I tried to launch the diffusion today, this is what it showed after a couple of minutes.
![image](https://user-images.githubusercontent.com/118744157/204373887-d58741d8-eef2-4210-abb7-8d845351a6b2.png)

Can you please direct me on how to set up the checkpoint?.. Because unfortunately, I have no clue...

**Comment by misobarisic** [comment]
You need to put a checkmark on any of these
![image](https://user-images.githubusercontent.com/50531162/204375186-5f8fcba8-d5d5-4799-b96e-cb7d22f29ef1.png)

**Comment by MrOuke** [comment]
Thank you for your quick and effective reply! Much appreciate it!^^
