### ISSUE TITLE
Xformers error fixed pleasee

### ISSUE THREAD

**Issue by Irahsanasah** [misobarisic/Diffusion-UI#20]

**Comment by misobarisic** [comment]
What is the error? I am not experiencing any xformers errors

**Comment by Irahsanasah** [comment]
> What is the error? I am not experiencing any xformers errors

Now working ... thank you.

I don't know why but before the gradi link did not want to appear and i saw a xformer error notif,

I try re -loaded and deleted the colab session,but still not working ... Maybe because of effect seeing many xformers errors in colab, So i think this was also due to the same thing ...

but i think this my mistake, sorry 🙏
