### ISSUE TITLE
You may be executing code that is disallowed, and this may restrict your ability to use Colab in the future. Please note the prohibited actions specified in our FAQ.

### ISSUE THREAD

**Issue by qa13683954882** [misobarisic/Diffusion-UI#27]
https://github.com/TheLastBen/fast-stable-diffusion/issues/2013

https://github.com/TheLastBen/fast-stable-diffusion

Someone has solved this problem

**Comment by qa13683954882** [comment]
> Google Colab ( https://research.google.com/colaboratory/faq.html ) ，它已经开始禁止使用隧道。
> 
> https://github.com/TheLastBen/fast-stable-diffusion
> 
> 有人已经解决了这个问题。但是需要更改代码

**Comment by misobarisic** [comment]
Will add a notice about it being against the TOS and use a workaround
