### ISSUE TITLE
Low quality pictures...

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#3]
I'm truly sorry about posting these issues here left and right... but there is no one other I turn for help...

So as of late, that means like two days ago, since the newest update to the collab, I tried to generate images again with the same settings as usual, however for some odd reasons that I do not understand, it's been giving me much lower quality images... to be specific, they are really low saturated for some reason... I will attach two pictures for close comparison, one will be before and the other after... And yes, I tried to tinker with the settings, even used other models and parameters but nothing worked... I use Anything3 model, if that helps but it did with the others when I tried them out as well...

Here are the images: The upper one is BEFORE (good one) and the bottom one is AFTER (bad one)
![409bbbbb91](https://user-images.githubusercontent.com/118744157/204599509-3d8e31e2-cfba-440e-9000-e4c2b8423fb3.png)
![406aa](https://user-images.githubusercontent.com/118744157/204599628-231b9e16-9b72-41b3-9e14-6594641f881c.png)

I'm not sure if it's just me but to me it seem like the bottom one has much less gloss and saturation then the first one... I tried all the settings but nothing seems to fixed it, I even tried different sampling methods but that didn't work either... I know I'm probably doing something wrong but I'm clueless as to what...

**Comment by misobarisic** [comment]
Are you using the same vae as before? A few commits ago I changed anime vae to be `off` by default. Reverted it back to defaulting to anime vae but the input is now a spinner dropdown instead of 2 separate checkboxes.

**Comment by MrOuke** [comment]
Actually I tried them both. Before you changed it to the dropdown box, there were two and I tried both separately one at a time but that didn't help... honestly speaking, I'm not sure what I had before, I never tinkered with it so I should have always just gone with the defaults... whatever they were...

**Comment by MrOuke** [comment]
Alright, I tried it now and it seems like you fixed it by changing the vae input... not really sure why didnt it work before but that dropdown box did the trick, now when I selected the vae option: "Anime" it works just like it did before! So thank you!... again^^
