### ISSUE TITLE
Yet another error has occurred...

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#4]
Again, I'm reaching up to you for yet another issue that popped up out of nowhere...

I think I'll just leave this image here and it should tell you enough about the error... at least I hope it will.
![image](https://user-images.githubusercontent.com/118744157/204826863-99298aa6-301d-46bf-b618-303ecd05fccb.png)

It shows up almost towards the end of the booting sequence.

P.S.: I'm sorry for having so many issues... >.>

**Comment by misobarisic** [comment]
> P.S.: I'm sorry for having so many issues... >.>

No need to be sorry ^^

The source repo for hd has a different name on huggingface now. HDv17 was also released 10 days ago. I have updated the notebook to use the new repo url alongside using the newest checkpoint.

Let me know if you need any help or would like to see any additions to the notebook.

**Comment by MrOuke** [comment]
Will do! Thank you again!^^
