### ISSUE TITLE
Progress Bar being interrupted

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#6]
Hello again. I came across this strange issue just now. I'm not sure what could be the cause for it but this time, the progress bar while it's generating images is getting interrupted repeatedly. I tried closing all programs and everything cause I thought it might be an issue with my RAM usage or something that hinders performance... but it didn't work. I haven't changed anything in the settings, still using everything as always... it just suddenly started to freeze while generating images.

For reference, this is the progress bar I'm talking about:
![image](https://user-images.githubusercontent.com/118744157/205515682-a4d98a43-0977-441e-ac6e-af292dcd916e.png)

What do you think could be the issue?

**Comment by misobarisic** [comment]
Have been experiencing this issue for some time. I don't think it's anything on my side that's malfunctioning. Probably an issue in the webui repo itself

**Comment by misobarisic** [comment]
Have been experiencing this issue for some time. I don't think it's anything on my side that's malfunctioning. Probably an issue in the webui repo itself.

**Comment by MrOuke** [comment]
Is there anything I could try to do to resolve this issue maybe? Or I just have to wait and try again later? Because even when I refreshed the whole system, it was still freezing, and by refresh I mean I started up the whole collab anew. So I don't really know, but this is the first time I have came across this, I mean I saw it getting stuck before but not as much and consistently as now...

**Comment by misobarisic** [comment]
@MrOuke the workaround is pressing `Shift+Enter` in the prompt input box. The issue of the progress bar not being real is  still here but at least new images can be generated in the same browser tab session
