### ISSUE TITLE
Another RunTime Error...

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#7]
I've just encountered this error randomly now... I believe it's somehow related to xformers again...
![image](https://user-images.githubusercontent.com/118744157/206304042-612ad836-cd84-4bcd-88ee-ad03c46dc5fb.png)

I tried running it without xformers enabled and it worked normally... so yeah, something is wrong with xformers again I'm afraid...

**Comment by IPdotSetAF** [comment]
> I've just encountered this error randomly now... I believe it's somehow related to xformers again... ![image](https://user-images.githubusercontent.com/118744157/206304042-612ad836-cd84-4bcd-88ee-ad03c46dc5fb.png)
> 
> I tried running it without xformers enabled and it worked normally... so yeah, something is wrong with xformers again I'm afraid...

same here but when i disable xformers it starts calculationg but in the end still throws the error

**Comment by misobarisic** [comment]
Looking into it right now. Do you by any chance remember the version of cuda which was being used prior to this error occuring? Information is provided by the first cell but I never run it so can't remember

**Comment by MrOuke** [comment]
> Looking into it right now. Do you by any chance remember the version of cuda which was being used prior to this error occuring? Information is provided by the first cell but I never run it so can't remember

Sorry, I have no idea. I ain't running that cell either. Only when there is some error that pops up during the booting sequence, but it never actually helped... So no, unfortunately, I don't remember the cuda version. :/

**Comment by misobarisic** [comment]
As it turns out, the guy who provides prebuilt xformers wheel packages had already built a compatible one. Pushed to main
